### ISSUE TITLE
Use case 2: Migration of JBDS Based VDB

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#62]
see https://docs.google.com/document/d/1N_2YpFdnoRhMInmESEHk01TtCGm9hfursM0MPLQwVSs/edit#bookmark=id.dg38o69wu4ld

allow migration of .vdb to .ddl

**Comment by apupier** [comment]
Ramesh said:
> a class by name "org.teiid.runtime.util.ConvertVDB" in "teiid-runtime", which can be used here.

**Comment by apupier** [comment]
https://mvnrepository.com/artifact/org.teiid/teiid-runtime

**Comment by apupier** [comment]
file used for test in teiid https://github.com/teiid/teiid/blob/teiid-parent-13.0.2/runtime/src/test/resources/portfolio-vdb.xml

**Comment by apupier** [comment]
@rareddy Seems the ConvertVDB is taking `.xml` files as input see [here](https://github.com/teiid/teiid/blob/404590eb558db86f30424efa86fb73820ef8a1c3/runtime/src/test/java/org/teiid/metadatastore/TestDDLMetadataStore.java#L308) and [here](https://github.com/teiid/teiid/blob/3a9139e41c9721e4c41ff981ff57b7ca6899610d/runtime/src/main/java/org/teiid/runtime/util/ConvertVDB.java#L60) but in [use case doc](https://docs.google.com/document/d/1N_2YpFdnoRhMInmESEHk01TtCGm9hfursM0MPLQwVSs/edit#bookmark=id.dg38o69wu4ld), it is mentioning a `.vdb` file

One is wrong? or both files exists? What is the link between them?

**Comment by rareddy** [comment]
Previously we had .vdb (binary) and then XML based and finally ended up at pure DDL file. So, both XML => DDL is also applicable, as well as VDB => DDL. As it turns out VDB=>DDL currently we have done two steps, VDB=>XML=>DDL. I have to find where we are doing the first part of it. I know we do it Teiid Designer tool, but we need to see if we pulled that into a utility class. Lets start with XML => DDL, I will figure out what is needed and update this issue.

**Comment by lhein** [comment]
Please create a FUSETOOLS2 issue for this.

**Comment by apupier** [comment]
corresponding JIRA issue https://issues.redhat.com/browse/FUSETOOLS2-371
